### ISSUE TITLE
Did access.watch shut down?

### ISSUE THREAD

**Issue by gonedjur** [access-watch/access-watch#246]
Wrong forum but did access.watch shut down its operations?

**Comment by znarf** [comment]
The present:

- Access Watch (the company) is suspending its operations due to lack of funds
- Access Watch (the service) is still operating but some things are broken due to lack of resources

The future:
- Access Watch (the open source software) is still there to be used by anyone
- Access Watch (the service) needs to be simplified to be relaunched as a service by the community for the community
