### ISSUE TITLE
Input incoming count

### ISSUE THREAD

**Issue by znarf** [access-watch/access-watch#77]
On a low traffic website, Input usually display 0 requests / sec.

It would be more helpful to have an average over the latest X minutes

Also:
- maybe change the metric to requests / min for consistency within the interface
- maybe keep and expose the 24 hours count

**Comment by benfle** [comment]
What is the purpose of this data?

1. Showing that the input is working
2. Showing the rate of requests going through

I agree that instantaneous values do not make sense.

If we want to keep a single numbers we could record the speed per minute and decide what unit to show based on the rate of traffic on the website.

Otherwise we could also show the trends for the recent past. We could easily record the number of requests per minute for the last hour and show a sparkline with this data.

**Comment by znarf** [comment]
Like everywhere else, let's expose a speed object with:
 - per_minute metrics over 15 minutes
 - per_hour metrics over 24 hours

**Comment by benfle** [comment]
On it.

**Comment by benfle** [comment]
@znarf?

![screen shot 2017-12-13 at 10 25 24 am](https://user-images.githubusercontent.com/24562/33949680-f6d79d30-dfef-11e7-902a-f1c599474db4.png)
