### ISSUE TITLE
Make metrics retention configurable (now 24h)

### ISSUE THREAD

**Issue by realies** [access-watch/access-watch#98]
Currently, it's only possible to view stats since the start of the app or the past 24 hours if the app was running for that long. In a case of usage with [a container](https://hub.docker.com/r/realies/access-watch/), the statistics are cleared upon restarting it, which is the same behaviour if you restart the app itself.

Edit: Upon refreshing the latest requests web page they disappear?!

**Comment by znarf** [comment]
Thank you for the feedback, I think there are 3 issues being discussed here.

1) the 24 hours limit: at this stage, because we focus more on real time and we have a simple storage system, we decided to have this 24 hours limit in the metrics: https://github.com/access-watch/access-watch/blob/master/lib/metrics.js#L167 Perhaps we could make that retention configurable.

2) metrics persistence: our storage is in memory based and is dumped on disk when the process is stopping (in the 'data' folder). It should then be reloaded on next restart. So, I'm not sure about the Docker use case, but there should be a way to make it work.

3) requests storage: at this stage, the Access Watch (on node.js side) is not storing the requests. The requests are flowing to the interface (react side) using Websocket, and the interface is holding the latest requests in its own memory. This is why they disappear on reload. This will be fixed in the future when we'll introduce some optional storage for the requests (perhaps based on Elasticsearch).

**Comment by realies** [comment]
Great to hear. Strange to see the data folder empty after running for a few days and restarting the container throughout the period. It would be good if there is access to older requests, perhaps through a filter.

**Comment by realies** [comment]
Noticed that the Robots/Addresses sections show the number of robot requests and their percentage with a `No robots/addresses seen for this period` text beneath. Is the latter section currently consuming real-time input and not relying on log data?

**Comment by znarf** [comment]
@realies about your latest Robots/Addresses, can you create a new issue and share a screenshot?

**Comment by znarf** [comment]
Let's make the 24 hours retention configurable. Once done, let's check how it behaves in production with 7 days retention.

**Comment by znarf** [comment]
See https://github.com/access-watch/access-watch/blob/master/docs/configuration.md for documentation.

**Comment by realies** [comment]
Is retention configured to 24h by default now?
